ERROR: setUpClass (__main__.TestFIXSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "fix_test_suite.py", line 75, in setUpClass
    cls.initiator = fix.SocketInitiator(cls.app, cls.storeFactory, cls.settings, cls.logFactory)
  File "/usr/local/lib64/python3.6/site-packages/quickfix.py", line 39997, in __init__
    SocketInitiatorBase.__init__(self, application, storeFactory, settings, logFactory)
  File "/usr/local/lib64/python3.6/site-packages/quickfix.py", line 39742, in __init__
    this = _quickfix.new_SocketInitiatorBase(*args)
quickfix.ConfigError: Configuration failed: FileStorePath not defined

----------------------------------------------------------------------
Ran 0 tests in 0.006s
